name: Sync to GitLab

on:
  push:
    branches:
      - master  # This is the GitHub branch, change it to 'main' if needed

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v3

      - name: Install Git
        run: sudo apt-get update && sudo apt-get install -y git

      - name: Mirror to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git config --global user.email "devendra@example.com"
          git config --global user.name "Devendra Sutar"
          git remote add gitlab https://oauth2:${GITLAB_TOKEN}@gitlab.com/devendra-sutar/bash.git
          git fetch --unshallow  # Fetch the full history if shallow clone was used
          git push --mirror gitlab
